FROM registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f AS builder

# Set env vars
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT

# Change the user to root
USER root

# Copy all files into the working directory
COPY . $APP_ROOT/src/

# Allow git to trust the directory
RUN git config --global --add safe.directory /opt/app-root/src

# Build binaries and ensure all dependencies are up to date
RUN make all

# Run the tests
CMD [ "go", "test", "./..." ]
