apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rekor-e2e-test
  annotations:
    tekton.dev/title: "Rekor e2e test"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-e2e-test
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        git config --global --add safe.directory /workspace/source
        tests/rhtap-e2e-test/e2e-test.sh

  sidecars:
    - name: mysql
      image: gcr.io/trillian-opensource-ci/db_server:v1.4.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: zaphod
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: zaphod

    - name: redis-server
      image: docker.io/redis:6.2
      args: [
        "--bind",
        "0.0.0.0",
        "--appendonly",
        "yes"
      ]
      ports:
        - containerPort: 6379

    - name: trillian-log-server
      image: gcr.io/projectsigstore/trillian_log_server@sha256:f850a0defd089ea844822030c67ae05bc93c91168a7dd4aceb0b6648c39f696b
      args: [
        "--storage_system=mysql",
        "--mysql_uri=test:zaphod@tcp(mysql:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--alsologtostderr",
      ]
      ports:
        - containerPort: 8090
        - containerPort: 8091

    - name: trillian-log-signer
      image: gcr.io/projectsigstore/trillian_log_signer@sha256:fe90d523f6617974f70878918e4b31d49b2b46a86024bb2d6b01d2bbfed8edbf
      args: [
        "--storage_system=mysql",
        "--mysql_uri=test:zaphod@tcp(mysql:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--force_master",
        "--alsologtostderr",
      ]
      ports:
        - containerPort: 8091 

    - name: rekor server
      image: quay.io/japower/rekor-server_test@sha256:464a27571cf1e6a0f5112b0ffda01ac2386f799746f382346928681e0b78d75c
      args: [
        "rekor-server",
        "-test.coverprofile=rekor-server.cov",
        "serve",
        "--trillian_log_server.address=trillian-log-server",
        "--trillian_log_server.port=8090",
        "--redis_server.address=redis-server",
        "--redis_server.port=6379",
        "--rekor_server.address=0.0.0.0",
        "--rekor_server.signer=memory",
        "--enable_attestation_storage",
        "--attestation_storage_bucket=file:///var/run/attestations",
        "--max_request_body_size=32792576",
      ]
      ports:
        - containerPort: 3000
        - containerPort: 2112

# This file bundles the e2e tests for rekor. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/rekor-e2e-test:v1 -f .tekton/rekor-e2e-test.yaml'.
# This will generate a new SHA for the bundle. 
# Ensure that this new SHA is updated in the pull and push pipeline files for each component.