apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rekor-e2e-test
  annotations:
    tekton.dev/title: "Rekor e2e test"
spec:
  workspaces:
    - name: source

  sidecars:
    - name: mysql
      image: gcr.io/trillian-opensource-ci/db_server:v1.4.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: zaphod
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: zaphod
      ports:
        - containerPort: 3306

    - name: redis-server
      image: docker.io/redis:6.2
      args: [
        "--bind",
        "0.0.0.0",
        "--appendonly",
        "yes"
      ]
      ports:
        - containerPort: 6379

    - name: trillian-log-server
      image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logserver:build-58a79-1696502872
      workingDir: $(workspaces.source.path)
      command: ["/bin/sh", "-c", "sleep 60 && /trillian_log_server"]
      args: [
        "--storage_system=mysql",
        "--mysql_uri=test:zaphod@tcp(127.0.0.1:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--alsologtostderr",
      ]
      ports:
        - containerPort: 8090
        - containerPort: 8091
      
    - name: trillian-log-signer
      image: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/trillian-logsigner:build-38813-1696586021
      workingDir: $(workspaces.source.path)
      command: ["/bin/sh", "-c", "sleep 60 && /trillian_log_signer"]
      args: [
        "--storage_system=mysql",
        "--mysql_uri=test:zaphod@tcp(127.0.0.1:3306)/test",
        "--rpc_endpoint=0.0.0.0:8090",
        "--http_endpoint=0.0.0.0:8091",
        "--force_master",
        "--alsologtostderr",
      ]
      ports:
        - containerPort: 8091

    - name: rekor-server
      image: quay.io/japower/rekor-server_test@sha256:9c6a9692564c7a976b9e0802c5af763f625ca14b93bd2b1456e5f662f07ef6b7
      command: ["/bin/sh", "-c", "sleep 80"]
      workingDir: $(workspaces.source.path)
      args: [
        "rekor-server",
        "-test.coverprofile=rekor-server.cov",
        "serve",
        "--trillian_log_server.address=127.0.0.1",
        "--trillian_log_server.port=8090",
        "--redis_server.address=127.0.0.1",
        "--redis_server.port=6379",
        "--rekor_server.address=0.0.0.0",
        "--rekor_server.signer=memory",
        "--enable_attestation_storage",
        "--attestation_storage_bucket=file:///var/run/attestations",
        "--max_request_body_size=32792576",
      ]
      ports:
        - containerPort: 3000
        - containerPort: 2112
        
  steps:
    - name: run-e2e-test
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        git config --global --add safe.directory /workspace/source
        tests/rhtap-e2e-test/e2e-test.sh

# This file bundles the e2e tests for rekor. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/rekor-e2e-test:v1 -f .tekton/rekor-e2e-test.yaml'.
# This will generate a new SHA for the bundle. 
# Ensure that this new SHA is updated in the pull and push pipeline files for each component.