apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rekor-e2e-test
  annotations:
    tekton.dev/title: "Rekor e2e test"
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi9/go-toolset@sha256:e91cbbd0b659498d029dd43e050c8a009c403146bfba22cbebca8bcd0ee7925f
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        ./e2e-test.sh
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}

# This file bundles the e2e tests for rekor. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/rekor-e2e-test:v1 -f .tekton/rekor-e2e-test.yaml'.
# This will generate a new SHA for the bundle. 
# Ensure that this new SHA is updated in the pull and push pipeline files for each component.