kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: rekor-e2e-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
  tasks:

    - name: test
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
        steps:
          - name: test
            image: registry.access.redhat.com/ubi9/ubi-minimal@sha256:b40f52aa68b29634ff45429ee804afbaa61b33de29ae775568933c71610f07a4
            env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            script: |
              echo $SNAPSHOT