apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rekor-e2e-test
  annotations:
    tekton.dev/title: "Rekor e2e test"
spec:
  workspaces:
    - name: source
  params:
    - name: TEST_IMAGE_URL
      type: string
      description: The image url for the test image
      default: ""

  sidecars:
    - name: mysql
      image: registry.redhat.io/rhtas-tech-preview/trillian-database-rhel9@sha256:3e7210bd4943c266eabaee33a50d86241c66ed69463f208bcc0b0b7373c22af0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: zaphod
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: zaphod

    - name: redis-server
      image: registry.redhat.io/rhel9/redis-6@sha256:91b755b9fb09b7299896f9a90f7d2752fdba36a8e6e9b9d1ddc17f3f92466745

    - name: trillian-log-server
      image: registry.redhat.io/rhtas-tech-preview/trillian-logserver-rhel9@sha256:d6bebd674b5d66bb742bf96dbbea761e2fa73a9fabd9be8a48cefbfc906e990c
      workingDir: $(workspaces.source.path)/source
      command: 
        - "/bin/sh"
        - "-c"
        - 'sleep 60 && /trillian_log_server --storage_system=mysql --mysql_uri="test:zaphod@tcp(127.0.0.1:3306)/test" --rpc_endpoint=0.0.0.0:8090 --http_endpoint=0.0.0.0:8091 --alsologtostderr'

    - name: trillian-log-signer
      image: registry.redhat.io/rhtas-tech-preview/trillian-logsigner-rhel9@sha256:015f430f8f966d5cf83cdaad5ba5ca87dd75a83e64abd229c00ddd370f3c393b
      workingDir: $(workspaces.source.path)/source
      command: 
        - "/bin/sh"
        - "-c"
        - 'sleep 60 && /trillian_log_signer --force_master --storage_system=mysql --mysql_uri="test:zaphod@tcp(127.0.0.1:3306)/test" --rpc_endpoint=0.0.0.0:8092 --http_endpoint=0.0.0.0:8093 --alsologtostderr'

    - name: rekor-server
      image: $(params.TEST_IMAGE_URL)
      workingDir: $(workspaces.source.path)/source
      command: 
        - "/bin/sh"
        - "-c"
        - "sleep 80 && rekor-server -test.coverprofile=rekor-server.cov serve --trillian_log_server.address=127.0.0.1 --trillian_log_server.port=8090 --redis_server.address=127.0.0.1 --redis_server.port=6379 --rekor_server.address=0.0.0.0 --rekor_server.signer=memory --enable_attestation_storage --attestation_storage_bucket=file:///var/run/attestations --max_request_body_size=32792576"
                
  steps:
    - name: run-e2e-test
      image: $(params.TEST_IMAGE_URL)
      workingDir: $(workspaces.source.path)/source
      script: |
        #!/usr/bin/env sh
        chmod +x ./e2e-test.sh
        ./e2e-test.sh
      resources:
        limits:
          memory: 3Gi
        requests:
          memory: 512Mi

# This file bundles the e2e tests for rekor. 
# If any changes are made to this file, it must be pushed to Quay using the following command:
# 'tkn bundle push quay.io/securesign/rekor-e2e-test:latest -f .tekton/rekor-e2e-test.yaml'.