kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: rekor-e2e-test
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
  workspaces:
  - name: cluster-credentials
    optional: true
  tasks:
    - name: rekor-e2e-test
      description: Task for running the rekor e2e tests
      params:
      - name: SNAPSHOT
        value: $(params.SNAPSHOT)
      - name: NAMESPACE
        value: $(params.NAMESPACE)
      workspaces:
        - name: cluster-credentials
          optional: true
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: NAMESPACE
        workspaces:
        - name: cluster-credentials
          optional: true
        steps:
        - name: echo
          image: registry.access.redhat.com/ubi9/go-toolset@sha256:82d9bc5d3ceb43635288880f26207201e55d1c688a60ebbfff4f54d4963a62a1
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: NAMESPACE
            value: $(params.NAMESPACE)
          script: |
            echo "SNAPSHOT: $SNAPSHOT"
            echo "NAMESPACE: $NAMESPACE"
